"""add wish

Revision ID: 4b8e2961f12e
Revises: cb7ce328038d
Create Date: 2019-04-23 10:38:28.911702

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b8e2961f12e'
down_revision = 'cb7ce328038d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('wish', sa.String(length=200), nullable=True))
    op.create_index(op.f('ix_user_wish'), 'user', ['wish'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_wish'), table_name='user')
    op.drop_column('user', 'wish')
    # ### end Alembic commands ###
