"""new columns

Revision ID: c268f7acdf71
Revises: 4b8e2961f12e
Create Date: 2019-04-23 17:11:36.487942

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c268f7acdf71'
down_revision = '4b8e2961f12e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('building', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('flat', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('school', sa.String(length=64), nullable=True))
    op.add_column('user', sa.Column('street', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_user_building'), 'user', ['building'], unique=True)
    op.create_index(op.f('ix_user_flat'), 'user', ['flat'], unique=True)
    op.create_index(op.f('ix_user_school'), 'user', ['school'], unique=True)
    op.create_index(op.f('ix_user_street'), 'user', ['street'], unique=True)
    op.drop_index('ix_user_wish', table_name='user')
    op.create_index(op.f('ix_user_wish'), 'user', ['wish'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_wish'), table_name='user')
    op.create_index('ix_user_wish', 'user', ['wish'], unique=False)
    op.drop_index(op.f('ix_user_street'), table_name='user')
    op.drop_index(op.f('ix_user_school'), table_name='user')
    op.drop_index(op.f('ix_user_flat'), table_name='user')
    op.drop_index(op.f('ix_user_building'), table_name='user')
    op.drop_column('user', 'street')
    op.drop_column('user', 'school')
    op.drop_column('user', 'flat')
    op.drop_column('user', 'building')
    # ### end Alembic commands ###
